version: "3.5"
services:
    clickhouse:
        container_name: clickhouse
        image: yandex/clickhouse-server
        volumes:
            - .data/clickhouse:/var/lib/clickhouse
            - ./docker/clickhouse/clickhouse-user.xml:/etc/clickhouse-server/users.d/clickhouse-user.xml
            - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
        ports:
            - "8123:8123"
            - "9000:9000"
            - "9009:9009"

        ulimits:
            nproc: 65535
            nofile:
                soft: 262144
                hard: 262144
    nginx:
        image: nginx:1.19.2-alpine
        container_name: nginx
        working_dir: /app
        ports:
            - 8000:80
        volumes:
            - .:/app:delegated
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
        links:
            - web
        restart: always

    postgres:
        image: postgres:12-alpine
        container_name: postgres
        ports:
            - 55432:5432
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'supersecurepassword'
            POSTGRES_DB: 'postgres'
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - .data/psql:/var/lib/postgresql/data
        restart: always

    web: &app
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                APP_ENV: "local"
        container_name: landing
        working_dir: /app
        volumes:
            - .:/app:delegated
            - ./docker/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        restart: on-failure
        depends_on:
            - postgres
            - jrpc
        environment:
            APP_ENV: "local"
            APP_DEBUG: "true"

    web_test:
        <<: *app
        container_name: landing-test
        environment:
            APP_ENV: "testing"
        volumes:
            - .:/app:delegated
            - .data/phpstorm-coverage:/opt/phpstorm-coverage
        ports: [ ]
        entrypoint: ["php", "-m"]

    jrpc:
        image: alpine:3.14
        container_name: jrpc
        ports:
            - 8080:8080
        environment:
            CLICKHOUSE_HOST: "tcp://clickhouse:9000"
        depends_on:
            - clickhouse
        volumes:
            - ./jrpc-server/jrpc-server:/usr/bin/jrpc-server
        restart: always
        entrypoint: ["jrpc-server"]
